# Generated by Django 4.2.30 on 2026-07-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0003_order_paid_time_order_payment_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_state',
            field=models.CharField(choices=[('P', 'Pending'), ('PR', 'Processing'), ('C', 'Completed'), ('F', 'Failed')], db_index=True, default='P', max_length=10),
        ),
    ]
